### ISSUE TITLE
readme.mdに必要な情報を追加してほしい。

### ISSUE THREAD

**Issue by harumaki4185** [yadokari1130/EnderLink#3]
## 概要
具体的な対応osを記載してほしい。  
- windows 10では正常動作しましたが、windows server 2016では問題が複数見受けられました。  

 
### 実行環境
* windows server 2016  
* windows 10

**Comment by yadokari1130** [comment]
以下のcommitにおいて対応しました
https://github.com/yadokari1130/EnderLink/commit/c31f5b96595183ca0a41776b3dd3cf7cfea5e8e2
